### ISSUE TITLE
[Backend] OpenGraph not returning some URL information

### ISSUE THREAD

**Issue by burkeholland** [burkeholland/linky-link#7]
Some URL's are returning no information for certain fields. An example is the VS Code Prettier extension, which returns an icon, but no description or title. Other extensions in the gallery return open graph data just fine.

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by cecilphillip** [comment]
@burkeholland we can close this now right?

**Comment by burkeholland** [comment]
Yes. Let's close it for now.
